"""Add activation codes tables

Revision ID: a1b2c3d4e5f6
Revises: 9c3d4e5f6g7h
Create Date: 2026-01-29

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '9c3d4e5f6g7h'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create activation_codes and device_linking_codes tables."""
    # Create activation_codes table
    # These codes are generated by users on the website to link devices to their account
    op.create_table('activation_codes',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', UUID(as_uuid=True), nullable=False),
        sa.Column('code', sa.String(length=10), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('is_used', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column('used_device_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_codes_code'), 'activation_codes', ['code'], unique=True)
    op.create_index(op.f('ix_activation_codes_user_id'), 'activation_codes', ['user_id'], unique=False)

    # Create device_linking_codes table
    # These codes are generated by the app so users can link devices from the website
    op.create_table('device_linking_codes',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('device_id', sa.String(length=255), nullable=False),
        sa.Column('device_name', sa.String(length=255), nullable=True),
        sa.Column('platform', sa.String(length=50), nullable=True),
        sa.Column('code', sa.String(length=10), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('is_linked', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('linked_at', sa.DateTime(), nullable=True),
        sa.Column('linked_user_id', UUID(as_uuid=True), nullable=True),
        sa.Column('access_token', sa.String(length=500), nullable=True),
        sa.Column('refresh_token', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_linking_codes_code'), 'device_linking_codes', ['code'], unique=True)
    op.create_index(op.f('ix_device_linking_codes_device_id'), 'device_linking_codes', ['device_id'], unique=False)


def downgrade() -> None:
    """Drop activation codes tables."""
    op.drop_index(op.f('ix_device_linking_codes_device_id'), table_name='device_linking_codes')
    op.drop_index(op.f('ix_device_linking_codes_code'), table_name='device_linking_codes')
    op.drop_table('device_linking_codes')
    op.drop_index(op.f('ix_activation_codes_user_id'), table_name='activation_codes')
    op.drop_index(op.f('ix_activation_codes_code'), table_name='activation_codes')
    op.drop_table('activation_codes')
