import uuid
from datetime import datetime
from typing import TYPE_CHECKING
from sqlalchemy import String, DateTime, ForeignKey, Boolean
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID

from app.db.database import Base

if TYPE_CHECKING:
    from app.models.user import User


class ActivationCode(Base):
    """
    Activation codes allow users to link devices to their account without entering credentials.
    Users generate a code from their dashboard, then enter it in the app on the target device.
    """
    __tablename__ = "activation_codes"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    code: Mapped[str] = mapped_column(String(10), unique=True, nullable=False, index=True)  # Format: ABC-123
    expires_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    is_used: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    used_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    used_device_id: Mapped[str | None] = mapped_column(String(255), nullable=True)  # Device that redeemed the code
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="activation_codes")


class DeviceLinkingCode(Base):
    """
    Device linking codes are generated by the app when a user wants to link their device.
    The code is displayed on the device, and the user enters it on the website to link.
    This is the reverse flow of ActivationCode.
    """
    __tablename__ = "device_linking_codes"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    device_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    device_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    platform: Mapped[str | None] = mapped_column(String(50), nullable=True)
    code: Mapped[str] = mapped_column(String(10), unique=True, nullable=False, index=True)  # Format: ABC-123
    expires_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    is_linked: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    linked_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    linked_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    # Store tokens after linking so app can retrieve them
    access_token: Mapped[str | None] = mapped_column(String(500), nullable=True)
    refresh_token: Mapped[str | None] = mapped_column(String(500), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    linked_user: Mapped["User | None"] = relationship("User")
